In [215]:
import nltk


# tokenize

In [216]:

from nltk.tokenize import word_tokenize
sms = ('One evening Frodo and Sam were walking together in the cool twilight')

tokenized_sms = word_tokenize(sms)
tokenized_sms

['One',
 'evening',
 'Frodo',
 'and',
 'Sam',
 'were',
 'walking',
 'together',
 'in',
 'the',
 'cool',
 'twilight']

# stopwords

In [217]:
from nltk.corpus import stopwords 
stopwor_sms=[]
stop_sm=stopword_sms 
stop_sm

[['evening', 'and', 'were', 'together', 'the', 'twilight']]

# Stemmer

In [218]:
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()
stemm = (tokenized_sms)
for stemm in stemm :
    stemm = stemmer.stem(stemm)
    print(stemmer.stem(stemm))

one
even
frodo
and
sam
were
walk
togeth
in
the
cool
twilight


# lemmatize

In [219]:
from nltk.stem import *
stemmer = WordNetLemmatizer()
plurals = tokenized_sms
for plurals in plurals :
    print(stemmer.lemmatize(plurals))

One
evening
Frodo
and
Sam
were
walking
together
in
the
cool
twilight


# خروجی استریم را وارد لیست می کنیم

In [220]:
from nltk.stem.porter import PorterStemmer
stemmer = PorterStemmer()

for i in range(len(tokenized_sms)):
    tokenized_sms[i] = stemmer.stem(tokenized_sms[i])
    
tokenized_sms

['one',
 'even',
 'frodo',
 'and',
 'sam',
 'were',
 'walk',
 'togeth',
 'in',
 'the',
 'cool',
 'twilight']

In [221]:
# from autocorrect import spell
# tokenized_sms[i] = stemmer.stem(spell(tokenized_sms[i]))

In [222]:
# sms_text = " ".join(tokenized_sms)
# sms_text

# one hot

In [223]:
# from sklearn.feature_extraction.text import CountVectorizer
# matrix = CountVectorizer(max_features=12)
# X = matrix.fit_transform(tokenized_sms).toarray()
# X

# bag of words

In [240]:
  # Feature extraction from text
# Method: bag of words 
# https://pythonprogramminglanguage.com

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
print( vectorizer.fit_transform(tokenized_sms).todense() )
print( vectorizer.vocabulary_ )
vectorizer.vocabulary_

[[0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0]]
{'one': 5, 'even': 2, 'frodo': 3, 'and': 0, 'sam': 6, 'were': 11, 'walk': 10, 'togeth': 8, 'in': 4, 'the': 7, 'cool': 1, 'twilight': 9}


{'one': 5,
 'even': 2,
 'frodo': 3,
 'and': 0,
 'sam': 6,
 'were': 11,
 'walk': 10,
 'togeth': 8,
 'in': 4,
 'the': 7,
 'cool': 1,
 'twilight': 9}

# Bag of nouns

In [241]:
nouns = []
for tokenized_sms in tokenized_sms:
     for word,pos in nltk.pos_tag(nltk.word_tokenize(str(tokenized_sms))):
            if (pos == 'NN' or pos == 'NNP' or pos == 'NNS' or pos == 'NNPS'):
                nouns.append(word)
nouns

['frodo', 'sam', 'walk', 'togeth', 'cool', 'twilight']

# Boolean retrieval model

# IDF

In [302]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.datasets import fetch_20newsgroups                # DOWNLOAD DATA SET
twenty = fetch_20newsgroups()

tfidf = TfidfVectorizer().fit_transform(twenty.data)         #   همه لغات tfidf محاسبه 

print (twenty.data[0]) # تست 
tfidf

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----







<11314x130107 sparse matrix of type '<class 'numpy.float64'>'
	with 1787565 stored elements in Compressed Sparse Row format>

In [293]:
tfidf[0:1]   # انتخاب مقدار مشخصی از tfidf
print(tfidf[0:1])
tfidf[0:1]

  (0, 56979)	0.0574701540748513
  (0, 75358)	0.3538350134970617
  (0, 123162)	0.25970902457356887
  (0, 118280)	0.21186807208281694
  (0, 50527)	0.05461428658858725
  (0, 124031)	0.10798795154169123
  (0, 85354)	0.03696978508816317
  (0, 114688)	0.06214070986309587
  (0, 111322)	0.019156718024950434
  (0, 123984)	0.036854292634593756
  (0, 37780)	0.3813389125949312
  (0, 68532)	0.07325812342131598
  (0, 114731)	0.1444727551278406
  (0, 87620)	0.0356718631408158
  (0, 95162)	0.03447138409326312
  (0, 64095)	0.035420924271313554
  (0, 98949)	0.16068606055394935
  (0, 90379)	0.01992885995664587
  (0, 118983)	0.03708597805061915
  (0, 89362)	0.06521174306303765
  (0, 79666)	0.10936401252414275
  (0, 40998)	0.07801368196918111
  (0, 92081)	0.09913274493911224
  (0, 76032)	0.01921946305222309
  (0, 4605)	0.06332603952480324
  :	:
  (0, 37565)	0.03431760442478462
  (0, 113986)	0.17691750674853085
  (0, 83256)	0.08844382496462175
  (0, 86001)	0.07000411445838192
  (0, 51730)	0.0971474405797672

<1x130107 sparse matrix of type '<class 'numpy.float64'>'
	with 89 stored elements in Compressed Sparse Row format>

In [294]:
from sklearn.metrics.pairwise import linear_kernel
cosine_similarities = linear_kernel(tfidf[0:1], tfidf).flatten()
cosine_similarities

array([1.        , 0.04405974, 0.11017033, ..., 0.04433678, 0.04457107,
       0.0329325 ])

In [295]:
related_docs_indices = cosine_similarities.argsort()[:-5:-1]
related_docs_indices

array([    0,   958, 10576,  3277], dtype=int64)

In [296]:
cosine_similarities[related_docs_indices]

array([1.        , 0.54967949, 0.32902198, 0.28257872])

[]